config/routes.rb
Rails.application.routes.draw do

  root 'games#game'

  get 'game' => 'games#game'
  get 'score' => 'games#score'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
# require 'open-uri'
# require 'json'
require 'longest_word'

class GamesController < ApplicationController

  def game
    @grid = LongestWord.generate_grid(10)
    # translation(attempt)
  end

  def score
    @end_time = Time.now
    @translation = LongestWord.translation(params[:attempt])
    @time = @end_time - Time.parse(params[:start_time])
    @process = LongestWord.process_translation(params[:attempt], @time)
    @score = params[:attempt].length + 1 / @time
  end

  # private

  # def generate_grid(grid_size)
  # # TODO: generate random grid of letters
  #   (0...grid_size).map { (65 + rand(26)).chr }
  # end

  # def translation(attempt)
  #   api_url = "http://api.wordreference.com/0.8/80143/json/enfr/#{attempt}"
  #   open(api_url) do |stream|
  #     quote = JSON.parse(stream.read)
  #     if quote['term0']
  #       quote['term0']['PrincipalTranslations']['0']['FirstTranslation']['term']
  #     end
  #   end
  # end

  # def process_translation(attempt, time)
  #   if translation(attempt)
  #     translation = translation(attempt)
  #     @score = attempt.length + 1 / time
  #     return { time: time, translation: translation, score: @score, message: "well done" }
  #   else
  #     return { time: 0, translation: nil, score: 0, message: "not an english word" }
  #   end
  # end

  # def run_game(attempt, grid, start_time, end_time)
  #   # TODO: runs the game and return detailed hash of result
  #   user_input = attempt.upcase.split("")
  #   if (grid - user_input).size <= grid.size - user_input.size # word in the grid
  #     time = end_time - start_time
  #     process_translation(attempt.downcase, time)
  #   else
  #     return { time: 0, translation: "", score: 0, message: "not in the grid" }
  #   end
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/game.html.erb
<%= @grid %>

<form action="/score">
  <input type="text" name="attempt">
  <input type="hidden" value="<%= Time.now %>" name="start_time">
  <input type="submit" value="Send">
</form>

app/views/games/score.html.erb
<h3>Congrats ! Here's how you did</h3>
<ul>
  <li><%= @translation %></li>
  <li><%= @time %> seconds</li>
  <li>Your score is <%= @score.round(2) %></li>
</ul>

<%= link_to "Play again", game_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Longestwordgame</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<h1>Longest Word Game</h1>
<%= yield %>

</body>
</html>